-- MySQL Script generated by MySQL Workbench
-- Fri Oct  5 21:17:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema petchoppbase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema petchoppbase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `petchoppbase` DEFAULT CHARACTER SET utf8 ;
USE `petchoppbase` ;

-- -----------------------------------------------------
-- Table `petchoppbase`.`Produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petchoppbase`.`Produtos` ;

CREATE TABLE IF NOT EXISTS `petchoppbase`.`Produtos` (
  `idProdutos` BIGINT NOT NULL,
  `Codigo` VARCHAR(25) NOT NULL,
  `Nome` VARCHAR(150) NOT NULL,
  `Preco` DOUBLE NOT NULL,
  `Custo` DOUBLE NOT NULL,
  `dtCompra` DATE NOT NULL,
  `dtValidade` DATE NULL,
  `urlImagem` VARCHAR(150) NULL,
  PRIMARY KEY (`idProdutos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petchoppbase`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petchoppbase`.`Endereco` ;

CREATE TABLE IF NOT EXISTS `petchoppbase`.`Endereco` (
  `idEndereco` BIGINT NOT NULL,
  `CEP` VARCHAR(10) NOT NULL,
  `Logradouro` VARCHAR(150) NOT NULL,
  `Bairro` VARCHAR(150) NOT NULL,
  `Cidade` VARCHAR(150) NOT NULL,
  `UF` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petchoppbase`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petchoppbase`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `petchoppbase`.`Cliente` (
  `idCliente` BIGINT NOT NULL,
  `dtCadastro` DATE NULL,
  `Nome` VARCHAR(100) NULL,
  `dtNasc` DATE NULL,
  `RG` VARCHAR(10) NULL,
  `CPF` VARCHAR(11) NULL,
  `Email` VARCHAR(100) NULL,
  `Senha` VARCHAR(100) NULL,
  `Ativo` BIT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petchoppbase`.`Vendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petchoppbase`.`Vendas` ;

CREATE TABLE IF NOT EXISTS `petchoppbase`.`Vendas` (
  `idVendas` BIGINT NOT NULL,
  `Data` DATETIME NOT NULL,
  `ValorTotal` DOUBLE NOT NULL,
  PRIMARY KEY (`idVendas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petchoppbase`.`ItemVendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petchoppbase`.`ItemVendas` ;

CREATE TABLE IF NOT EXISTS `petchoppbase`.`ItemVendas` (
  `idVendas` BIGINT NOT NULL,
  `idProdutos` BIGINT NOT NULL,
  `Quantidade` INT NOT NULL,
  `Valor` DOUBLE NOT NULL,
  CONSTRAINT `fk_ItemVendas_1`
    FOREIGN KEY (`idVendas`)
    REFERENCES `petchoppbase`.`Vendas` (`idVendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItemVendas_2`
    FOREIGN KEY (`idProdutos`)
    REFERENCES `petchoppbase`.`Produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petchoppbase`.`Tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petchoppbase`.`Tipo` ;

CREATE TABLE IF NOT EXISTS `petchoppbase`.`Tipo` (
  `idTipo` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petchoppbase`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petchoppbase`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `petchoppbase`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `idTipo` INT NOT NULL,
  PRIMARY KEY (`idCategoria`),
  CONSTRAINT `fk_Categoria_1`
    FOREIGN KEY (`idTipo`)
    REFERENCES `petchoppbase`.`Tipo` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Categoria_1_idx` ON `petchoppbase`.`Categoria` (`idTipo` ASC);


-- -----------------------------------------------------
-- Table `petchoppbase`.`Tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petchoppbase`.`Tags` ;

CREATE TABLE IF NOT EXISTS `petchoppbase`.`Tags` (
  `idTags` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`idTags`),
  CONSTRAINT `fk_Tags_1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `petchoppbase`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Tags_1_idx` ON `petchoppbase`.`Tags` (`idCategoria` ASC);


-- -----------------------------------------------------
-- Table `petchoppbase`.`ProdutoTags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petchoppbase`.`ProdutoTags` ;

CREATE TABLE IF NOT EXISTS `petchoppbase`.`ProdutoTags` (
  `idProdutos` BIGINT NOT NULL,
  `idTags` INT NOT NULL,
  CONSTRAINT `fk_ProdutoTags_1`
    FOREIGN KEY (`idProdutos`)
    REFERENCES `petchoppbase`.`Produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProdutoTags_2`
    FOREIGN KEY (`idTags`)
    REFERENCES `petchoppbase`.`Tags` (`idTags`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ProdutoTags_1_idx` ON `petchoppbase`.`ProdutoTags` (`idProdutos` ASC);

CREATE INDEX `fk_ProdutoTags_2_idx` ON `petchoppbase`.`ProdutoTags` (`idTags` ASC);


-- -----------------------------------------------------
-- Table `petchoppbase`.`ClienteEndereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petchoppbase`.`ClienteEndereco` ;

CREATE TABLE IF NOT EXISTS `petchoppbase`.`ClienteEndereco` (
  `idCliente` BIGINT NOT NULL,
  `idEndereco` BIGINT NOT NULL,
  `idTipo` INT NOT NULL,
  CONSTRAINT `fk_ClienteEndereco_1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `petchoppbase`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ClienteEndereco_2`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `petchoppbase`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ClienteEndereco_3`
    FOREIGN KEY (`idTipo`)
    REFERENCES `petchoppbase`.`Tipo` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ClienteEndereco_1_idx` ON `petchoppbase`.`ClienteEndereco` (`idCliente` ASC);

CREATE INDEX `fk_ClienteEndereco_2_idx` ON `petchoppbase`.`ClienteEndereco` (`idEndereco` ASC);

CREATE INDEX `fk_ClienteEndereco_3_idx` ON `petchoppbase`.`ClienteEndereco` (`idTipo` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
