-- MySQL Script generated by MySQL Workbench
-- Sáb 06 Out 2018 13:42:05 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` BIGINT NOT NULL,
  `Codigo` VARCHAR(25) NOT NULL,
  `Nome` VARCHAR(150) NOT NULL,
  `Preco` DOUBLE NOT NULL,
  `Custo` DOUBLE NOT NULL,
  `dtCompra` DATE NOT NULL,
  `dtValidade` DATE NULL,
  `urlImagem` VARCHAR(150) NULL,
  `emEstoque` BIT NOT NULL,
  `Disable` BIT NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `idEndereco` BIGINT NOT NULL,
  `CEP` VARCHAR(10) NOT NULL,
  `Logradouro` VARCHAR(150) NOT NULL,
  `Bairro` VARCHAR(150) NOT NULL,
  `Cidade` VARCHAR(150) NOT NULL,
  `UF` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` BIGINT NOT NULL,
  `dtCadastro` DATE NULL,
  `Nome` VARCHAR(100) NULL,
  `dtNasc` DATE NULL,
  `RG` VARCHAR(10) NULL,
  `CPF` VARCHAR(11) NULL,
  `Email` VARCHAR(100) NULL,
  `Senha` VARCHAR(100) NULL,
  `Ativo` BIT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Venda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Venda` (
  `idVenda` BIGINT NOT NULL,
  `Data` DATETIME NOT NULL,
  `ValorTotal` DOUBLE NOT NULL,
  PRIMARY KEY (`idVenda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemVenda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ItemVenda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ItemVenda` (
  `idVenda` BIGINT NOT NULL,
  `idProduto` BIGINT NOT NULL,
  `Quantidade` INT NOT NULL,
  `Valor` DOUBLE NOT NULL,
  CONSTRAINT `fk_ItemVendas_1`
    FOREIGN KEY (`idVenda`)
    REFERENCES `mydb`.`Venda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItemVendas_2`
    FOREIGN KEY (`idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tipo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tipo` (
  `idTipo` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `idTipo` INT NOT NULL,
  PRIMARY KEY (`idCategoria`),
  INDEX `fk_Categoria_1_idx` (`idTipo` ASC),
  CONSTRAINT `fk_Categoria_1`
    FOREIGN KEY (`idTipo`)
    REFERENCES `mydb`.`Tipo` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tags` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tags` (
  `idTags` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`idTags`),
  INDEX `fk_Tags_1_idx` (`idCategoria` ASC),
  CONSTRAINT `fk_Tags_1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProdutoTags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ProdutoTags` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ProdutoTags` (
  `idProduto` BIGINT NOT NULL,
  `idTags` INT NOT NULL,
  INDEX `fk_ProdutoTags_1_idx` (`idProduto` ASC),
  INDEX `fk_ProdutoTags_2_idx` (`idTags` ASC),
  CONSTRAINT `fk_ProdutoTags_1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProdutoTags_2`
    FOREIGN KEY (`idTags`)
    REFERENCES `mydb`.`Tags` (`idTags`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ClienteEndereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ClienteEndereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ClienteEndereco` (
  `idCliente` BIGINT NOT NULL,
  `idEndereco` BIGINT NOT NULL,
  `idTipo` INT NOT NULL,
  INDEX `fk_ClienteEndereco_1_idx` (`idCliente` ASC),
  INDEX `fk_ClienteEndereco_2_idx` (`idEndereco` ASC),
  INDEX `fk_ClienteEndereco_3_idx` (`idTipo` ASC),
  CONSTRAINT `fk_ClienteEndereco_1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ClienteEndereco_2`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `mydb`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ClienteEndereco_3`
    FOREIGN KEY (`idTipo`)
    REFERENCES `mydb`.`Tipo` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StatusPedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`StatusPedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`StatusPedido` (
  `idStatusPedido` BIGINT NOT NULL,
  `idVenda` BIGINT NOT NULL,
  `idTipo` INT NOT NULL,
  `dtStatus` DATE NOT NULL,
  `Ativo` BIT NOT NULL,
  PRIMARY KEY (`idStatusPedido`),
  INDEX `fk_StatusPedido_1_idx` (`idVenda` ASC),
  CONSTRAINT `fk_StatusPedido_1`
    FOREIGN KEY (`idVenda`)
    REFERENCES `mydb`.`Venda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Estoque` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `idProduto` BIGINT NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`idProduto`),
  CONSTRAINT `fk_Estoque_1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`table1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MovimentoEstoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MovimentoEstoque` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MovimentoEstoque` (
  `idMovimento` BIGINT NOT NULL,
  `idProduto` BIGINT NOT NULL,
  `idTipo` INT NOT NULL,
  `dtMovimento` DATE NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`idMovimento`),
  INDEX `fk_MovimentoEstoque_1_idx` (`idProduto` ASC),
  INDEX `fk_MovimentoEstoque_2_idx` (`idTipo` ASC),
  CONSTRAINT `fk_MovimentoEstoque_1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MovimentoEstoque_2`
    FOREIGN KEY (`idTipo`)
    REFERENCES `mydb`.`Tipo` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
